### ISSUE TITLE
The css in not displayed

### ISSUE THREAD

**Issue by walidMyges** [waliidhakim/JsCalculator#9]
**Describe the bug**
it seems that the css is not properly loaded

**To Reproduce**
1. Go to home page, and see that there is no style

**Expected behavior**
Colors were displayed last i visited the web site

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by waliidhakim** [comment]
bug fixed
